"""EDIT ROUNDS HERE. Restart locally/redeploy, then create a NEW room.

kind: commit | code | text | image | audio
answer: AI | HUMAN (server-only; never placed in static files)
seconds: optional override for this round (5–120 seconds)
image_fit: contain | cover; image_position: CSS object-position
AI means generative-AI-produced. HUMAN includes ordinary camera photography.
"""

ROUNDS = [
    {
        "title": "A small fix, a big promise", "kind": "commit",
        "body": "fix(cache): stop treating empty results as cache misses\n\nUse an explicit sentinel so [] and None can be cached.\nKeeps repeated lookups from hammering the upstream service.",
        "answer": "AI",
        "explanation": "This commit message was generated by AI for the game. Specific implementation detail and a believable motivation can both be generated.",
        "source": "AI text generated for this game; no real repository or author implied.",
    },
    {
        "title": "Find the insertion point", "kind": "code",
        "body": "while lo < hi:\n    mid = (lo+hi)//2\n    if x < a[mid]: hi = mid\n    else: lo = mid+1\nreturn lo",
        "answer": "HUMAN",
        "explanation": "An excerpt from CPython 3.5.0's bisect_right implementation. Its compact style is historical human code, not evidence that terse code must be human.",
        "source": "CPython v3.5.0, Lib/bisect.py (2015), Python Software Foundation license. Excerpt omits surrounding setup and docstring.",
        "source_url": "https://github.com/python/cpython/blob/v3.5.0/Lib/bisect.py",
    },
    {
        "title": "Afternoon at the desk", "kind": "image",
        "media": "/static/images/sample03.jpg", "alt": "A keyboard, mug and open notebook on a sunlit desk.",
        "image_fit": "contain", "image_position": "center",
        "answer": "AI",
        "explanation": "This is a generated photograph. Warm sunlight, mundane clutter and camera-like texture are no longer reliable signs of a real camera capture.",
        "source": "Generated with OpenAI imagegen for this game, October 2026. Prompt recorded in ContentSources.md.",
    },
    {
        "title": "A mark in the dust", "kind": "image",
        "media": "/static/images/sample04.jpg", "alt": "A boot-shaped impression in a dusty surface.",
        "image_fit": "contain", "image_position": "center",
        "answer": "HUMAN",
        "explanation": "Buzz Aldrin photographed this bootprint during Apollo 11 in 1969. The unusual lighting and texture are real. Historical provenance establishes the origin.",
        "source": "NASA / Edwin Buzz Aldrin, AS11-40-5878, July 20, 1969.",
        "source_url": "https://science.nasa.gov/resource/apollo-11-bootprint/",
    },
    {
        "title": "One way to introduce a project", "kind": "commit",
        "body": 'Initial revision of "git", the information manager from hell',
        "answer": "HUMAN",
        "explanation": "The subject of Git's first commit, by Linus Torvalds in April 2005. The irreverent voice is real here, but tone alone cannot establish authorship.",
        "source": "git/git, initial commit e83c5163316f89bfbde7d9ab23ca2e25604af290, April 7, 2005. Subject only.",
        "source_url": "https://github.com/git/git/commit/e83c5163316f89bfbde7d9ab23ca2e25604af290",
    },
    {
        "title": "Retry, retry again", "kind": "code",
        "body": "def retry(fn, attempts=3):\n    for attempt in range(attempts):\n        try:\n            return fn()\n        except TimeoutError:\n            if attempt == attempts - 1:\n                raise",
        "answer": "AI",
        "explanation": "AI generated this short helper for the game. It looks idiomatic but has no delay or backoff, and attempts=0 silently returns None. Bugs do not prove human authorship.",
        "source": "AI code generated for this game; displayed as content and never executed.",
    },
    {
        "title": "Advice for the next review", "kind": "text",
        "body": "Errors should never pass silently.\nUnless explicitly silenced.\nIn the face of ambiguity, refuse the temptation to guess.",
        "answer": "HUMAN",
        "explanation": "These lines are from Tim Peters' Zen of Python, published in PEP 20. An AI can reproduce famous human text; this round classifies the original authored excerpt.",
        "source": "Tim Peters, PEP 20 (2004), public domain; short excerpt.",
        "source_url": "https://peps.python.org/pep-0020/",
    },
    {
        "title": "The incident channel", "kind": "text",
        "body": "14:07 — cache hit rate fell off a cliff.\n14:12 — rolled back the 'tiny' config change.\n14:19 — traffic is normal. Coffee is not.\nAction item: stop deploying optimism as configuration.",
        "answer": "AI",
        "explanation": "AI generated this fictional incident note. Humor, rough edges and casual engineer language can be prompted. No actual outage is described.",
        "source": "AI text generated for this game; fictional incident.",
    },
    {
        "title": "A blue world", "kind": "image",
        "media": "/static/images/sample09.jpg", "alt": "A full view of Earth in a scanned film photograph.",
        "image_fit": "contain", "image_position": "center",
        "answer": "HUMAN",
        "explanation": "The Apollo 17 crew took this photograph in December 1972. It is a camera photograph, not a generative image. Digital copies and display resizing do not change that origin.",
        "source": "NASA / Apollo 17 crew, AS17-148-22727, December 7, 1972; NASA Johnson Space Center.",
        "source_url": "https://science.nasa.gov/resource/the-blue-marble/",
    },
    {
        "title": "The last crossing", "kind": "image",
        "media": "/static/images/sample10.jpg", "alt": "Pedestrians with umbrellas crossing a wet city street at dusk.",
        "image_fit": "contain", "image_position": "center",
        "answer": "AI",
        "explanation": "This street scene was generated for the game. Reflections and candid composition can look convincing. Use provenance rather than a checklist of visual tells.",
        "source": "Generated with OpenAI imagegen for this game, October 2026. Prompt recorded in ContentSources.md.",
    },
]
